export const NAV_ITEMS = [
  { label: "Home", href: "#" },
  { label: "About Me", href: "#about" },
  { label: "Projects", href: "#projects" },
  { label: "Contact Me", href: "#contact" },
];

export const NAV_ITEM = {
  home: {
    label: "Home",
    href: "#",
  },
  about: {
    label: "About Me",
    href: "#about",
  },
  projects: {
    label: "Projects",
    href: "#projects",
  },
  contact: {
    label: "Contact Me",
    href: "#contact",
  },
};

export const SkillsIcons = [
  {
    id: 1,
    name: "Chakra-UI",
    label: "chakraui",
    path: "/img/skills/icon_chakraui.svg",
    position: {
      top: 130,
      left: 195,
    },
  },
  {
    id: 2,
    name: "React.js",
    label: "reactjs",
    path: "/img/skills/icon_reactjs.svg",
    position: {
      top: 225,
      left: 340,
    },
  },
  {
    id: 3,
    name: "Node.js",
    label: "nodejs",
    path: "/img/skills/icon_nodejs.svg",
    position: {
      top: 320,
      left: 305,
    },
  },
  {
    id: 4,
    name: "CSS3",
    label: "css3",
    path: "/img/skills/icon_css3.svg",
    position: {
      top: 308,
      left: 207,
    },
  },
  {
    id: 5,
    name: "MaterialUI",
    label: "materialui",
    path: "/img/skills/icon_materialui.svg",
    position: {
      top: 195,
      left: 110,
    },
  },
  {
    id: 6,
    name: "Python",
    label: "python",
    path: "/img/skills/icon_python.svg",
    position: {
      top: 205,
      left: 475,
    },
  },
  {
    id: 7,
    name: "HTML5",
    label: "html5",
    path: "/img/skills/icon_html5.svg",
    position: {
      top: 130,
      left: 305,
    },
  },
  {
    id: 8,
    name: "Sass",
    label: "sass",
    path: "/img/skills/icon_sass.svg",
    position: {
      top: 225,
      left: 225,
    },
  },
  {
    id: 9,
    name: "Next.js",
    label: "nextjs",
    path: "/img/skills/icon_nextjs.svg",
    position: {
      top: 55,
      left: 205,
    },
  },
  {
    id: 10,
    name: "TypeScript",
    label: "typescript",
    path: "/img/skills/icon_typescript.svg",
    position: {
      top: 75,
      left: 395,
    },
  },
  {
    id: 11,
    name: "Figma",
    label: "figma",
    path: "/img/skills/icon_figma.svg",
    position: {
      top: 295,
      left: 115,
    },
  },
  {
    id: 12,
    name: "Jest",
    label: "jest",
    path: "/img/skills/icon_jest.svg",
    position: {
      top: 375,
      left: 395,
    },
  },
  {
    id: 13,
    name: "Bootstrap5",
    label: "bootstrap5",
    path: "/img/skills/icon_bootstrap5.svg",
    position: {
      top: 395,
      left: 245,
    },
  },
  {
    id: 14,
    name: "Lua",
    label: "lua",
    path: "/img/skills/icon_lua.svg",
    position: {
      top: "383px",
      left: "134px",
    },
  },
  {
    id: 15,
    name: "Docker",
    label: "docker",
    path: "/img/skills/icon_docker.svg",
    position: {
      top: "150px",
      left: "414px",
    },
  },
  {
    id: 15,
    name: "Less",
    label: "less",
    path: "/img/skills/icon_less.svg",
    position: {
      top: "340px",
      left: "474px",
    },
  },
  {
    id: 16,
    name: "Webpack",
    label: "webpack",
    path: "/img/skills/icon_webpack.svg",
    position: {
      top: "110px",
      left: "84px",
    },
  },
  {
    id: 17,
    name: "Photoshop",
    label: "photoshop",
    path: "/img/skills/icon_photoshop.svg",
    position: {
      top: "280px",
      left: "404px",
    },
  },
];

export const ProjectsData = [
  {
    id: 1,
    name: "iUjex",
    title: "Local Transport Company Web App",
    description:
      "This project enhances user experience for customers and drivers by connecting them through a multi-role web application.",
    skillset: [
      "Using ",
      <strong key="1">React.js, TypeScript, Redux, and Sass</strong>,
      ", I implemented responsive interfaces and provide ongoing support to ensure the application functions correctly.",
    ],
    images: [
      {
        src: "/img/projects/iujex/iujex_1.jpg",
        width: 400,
        height: 284,
        alt: "iUjex Project 1",
        top: "40px",
        left: "-18px",
        zIndex: 5,
      },
      {
        src: "/img/projects/iujex/iujex_2.jpg",
        width: 150,
        height: 366,
        alt: "iUjex Project 2",
        top: "-22px",
        left: "-51px",
        zIndex: 4,
      },
      {
        src: "/img/projects/iujex/iujex_3.jpg",
        width: 370,
        height: 351,
        alt: "iUjex Project 3",
        top: "91px",
        left: "-80px",
        zIndex: 3,
      },
      {
        src: "/img/projects/iujex/iujex_4.jpg",
        width: 370,
        height: 318,
        alt: "iUjex Project 4",
        top: "115px",
        left: "30px",
        zIndex: 2,
      },
      {
        src: "/img/projects/iujex/iujex_5.jpg",
        width: 420,
        height: 267,
        alt: "iUjex Project 5",
        top: "-44px",
        left: "5px",
        zIndex: 1,
      },
    ],
    url: "https://iujex.com/",
    github:
      "https://gist.github.com/mantuok/04aa4a4d1b69752f71a4981847cdb85e.js",
  },
  {
    id: 2,
    name: "SafeHome SF",
    title: "Earthquake Preparedness Web App",
    description:
      "This project improves earthquake preparedness awareness in San Francisco with responsive user interfaces. ",
    skillset: [
      "Using ",
      <strong key="1">Next.js, TypeScript, and Chakra UI</strong>,
      ", I design an intuitive experience and ensure reliability through Jest testing.",
    ],
    images: [
      {
        src: "/img/projects/safehome/safehome_1.jpg",
        width: 400,
        height: 323,
        alt: "SafeHome SF project 1",
        top: "40px",
        left: "-18px",
        zIndex: 5,
      },
      {
        src: "/img/projects/safehome/safehome_2.jpg",
        width: 380,
        height: 281,
        alt: "SafeHome SF project 2",
        top: "-44px",
        left: "5px",
        zIndex: 4,
      },
      {
        src: "/img/projects/safehome/safehome_3.jpg",
        width: 300,
        height: 231,
        alt: "SafeHome SF project 3",
        top: "91px",
        left: "-80px",
        zIndex: 3,
      },
      {
        src: "/img/projects/safehome/safehome_4.jpg",
        width: 380,
        height: 292,
        alt: "SafeHome SF project 4",
        top: "145px",
        left: "30px",
        zIndex: 4,
      },
    ],
    url: "https://www.safehome.report/",
    github: "https://github.com/sfbrigade/datasci-earthquake",
  },
  {
    id: 3,
    name: "Liga Bank",
    title: "Local Bank Web App",
    description:
      "This project enhances the banking experience by providing tools for calculating mortgage and loan options.",
    skillset: [
      "Using ",
      <strong key="1">React, Redux, and Sass</strong>,
      ", I developed an  interface with efficient state management to ensure accurate calculations and a seamless user experience.",
    ],
    images: [
      {
        src: "/img/projects/ligabank/ligabank_1.jpg",
        width: 316,
        height: 199,
        alt: "Liga Bank Project 1",
        top: "110px",
        left: "22px",
        zIndex: 5,
      },
      {
        src: "/img/projects/ligabank/ligabank_2.jpg",
        width: 300,
        height: 170,
        alt: "Liga Bank Project 2",
        top: "37px",
        left: "5px",
        zIndex: 4,
      },
      {
        src: "/img/projects/ligabank/ligabank_3.jpg",
        width: 300,
        height: 175,
        alt: "Liga Bank Project 3",
        top: "181px",
        left: "-50px",
        zIndex: 3,
      },
      {
        src: "/img/projects/ligabank/ligabank_4.jpg",
        width: 300,
        height: 162,
        alt: "Liga Bank Project 4",
        top: "235px",
        left: "100px",
        zIndex: 2,
      },
    ],
    url: "",
    github: "https://github.com/mantuok/liga-bank",
  },
  {
    id: 4,
    name: "Avto Moto",
    title: "Car Dealership Website",
    description:
      "This project improves the user experience for car buyers by providing a platform to explore vehicles and read customer reviews.",
    skillset: [
      "Using ",
      <strong key="1">React, Redux, and Sass</strong>,
      ", I developed an  interface that allows seamless browsing and effective state management for enhanced functionality.",
    ],
    images: [
      {
        src: "/img/projects/avtomoto/avtomoto_1.jpg",
        width: 350,
        height: 201,
        alt: "Avto Moto Project 1",
        top: "110px",
        left: "22px",
        zIndex: 5,
      },
      {
        src: "/img/projects/avtomoto/avtomoto_2.jpg",
        width: 251,
        height: 187,
        alt: "Avto Moto Project 2",
        top: "37px",
        left: "5px",
        zIndex: 4,
      },
      {
        src: "/img/projects/avtomoto/avtomoto_3.jpg",
        width: 300,
        height: 182,
        alt: "Avto Moto Project 3",
        top: "181px",
        left: "-50px",
        zIndex: 3,
      },
      {
        src: "/img/projects/avtomoto/avtomoto_4.jpg",
        width: 250,
        height: 122,
        alt: "Avto Moto Project 4",
        top: "265px",
        left: "100px",
        zIndex: 2,
      },
    ],
    url: "",
    github: "https://github.com/mantuok/avto-moto",
  },
  {
    id: 5,
    name: "Cat Energy",
    title: "Cat Food Manufacturer Website",
    description:
      "This project provides a responsive and adaptive web site for innovative cat food  and facilitates orders through catalog and order form.",
    skillset: [
      "Using ",
      <strong key="1">HTML5, LESS, and BEM methodology</strong>,
      ", I implemented clean and maintainable code to create an engaging and user-friendly interface.",
    ],
    images: [
      {
        src: "/img/projects/catenergy/catenergy_1.jpg",
        width: 377,
        height: 207,
        alt: "Cat Energy Project 1",
        top: "110px",
        left: "22px",
        zIndex: 5,
      },
      {
        src: "/img/projects/catenergy/catenergy_2.jpg",
        width: 300,
        height: 164,
        alt: "Cat Energy Project 2",
        top: "37px",
        left: "5px",
        zIndex: 4,
      },
      {
        src: "/img/projects/catenergy/catenergy_3.jpg",
        width: 300,
        height: 169,
        alt: "Cat Energy Project 3",
        top: "181px",
        left: "-50px",
        zIndex: 3,
      },
      {
        src: "/img/projects/catenergy/catenergy_4.jpg",
        width: 300,
        height: 152,
        alt: "Cat Energy Project 4",
        top: "265px",
        left: "87px",
        zIndex: 2,
      },
    ],
    url: "https://mantuok.github.io/cat-energy/",
    github: "https://github.com/mantuok/cat-energy",
  },
  {
    id: 6,
    name: "Gllacy",
    title: "Ice-Cream Parlour Website",
    description:
      "This project enhances user experience for customers and drivers by connecting them through a multi-role web application.",
    skillset: [
      "Using ",
      <strong key="1">HTML5 and CSS3</strong>,
      ", I built a visually appealing interface to engage users and highlight the brand’s offerings.",
    ],
    images: [
      {
        src: "/img/projects/gllacy/gllacy_1.jpg",
        width: 372,
        height: 194,
        alt: "Gllacy Project 1",
        top: "110px",
        left: "22px",
        zIndex: 5,
      },
      {
        src: "/img/projects/gllacy/gllacy_2.jpg",
        width: 300,
        height: 165,
        alt: "Gllacy Project 2",
        top: "37px",
        left: "5px",
        zIndex: 4,
      },
      {
        src: "/img/projects/gllacy/gllacy_3.jpg",
        width: 300,
        height: 165,
        alt: "Gllacy Project 3",
        top: "181px",
        left: "-50px",
        zIndex: 3,
      },
      {
        src: "/img/projects/gllacy/gllacy_4.jpg",
        width: 300,
        height: 145,
        alt: "Gllacy Project 4",
        top: "265px",
        left: "87px",
        zIndex: 2,
      },
    ],
    url: "https://mantuok.github.io/gllacy-parlour/",
    github: "https://github.com/mantuok/gllacy-parlour",
  },
];
